# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hydraulics_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.u1Slider = QtWidgets.QSlider(self.centralwidget)
        self.u1Slider.setOrientation(QtCore.Qt.Horizontal)
        self.u1Slider.setObjectName("u1Slider")
        self.horizontalLayout_3.addWidget(self.u1Slider)
        self.spinBox_9 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_3.addWidget(self.spinBox_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.graphicsDisplay = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsDisplay.setObjectName("graphicsDisplay")
        self.verticalLayout_2.addWidget(self.graphicsDisplay)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.i1Group = QtWidgets.QVBoxLayout()
        self.i1Group.setObjectName("i1Group")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.i1Group.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.circle = QtWidgets.QRadioButton(self.centralwidget)
        self.circle.setChecked(True)
        self.circle.setObjectName("circle")
        self.intersection1Group = QtWidgets.QButtonGroup(MainWindow)
        self.intersection1Group.setObjectName("intersection1Group")
        self.intersection1Group.addButton(self.circle)
        self.horizontalLayout.addWidget(self.circle)
        self.rectangle = QtWidgets.QRadioButton(self.centralwidget)
        self.rectangle.setObjectName("rectangle")
        self.intersection1Group.addButton(self.rectangle)
        self.horizontalLayout.addWidget(self.rectangle)
        self.i1Group.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.i1ySlider = QtWidgets.QSlider(self.centralwidget)
        self.i1ySlider.setMaximum(200)
        self.i1ySlider.setOrientation(QtCore.Qt.Horizontal)
        self.i1ySlider.setObjectName("i1ySlider")
        self.gridLayout.addWidget(self.i1ySlider, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.i1wSlider = QtWidgets.QSlider(self.centralwidget)
        self.i1wSlider.setEnabled(True)
        self.i1wSlider.setMinimum(5)
        self.i1wSlider.setMaximum(150)
        self.i1wSlider.setOrientation(QtCore.Qt.Horizontal)
        self.i1wSlider.setObjectName("i1wSlider")
        self.gridLayout.addWidget(self.i1wSlider, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.i1wLabel = QtWidgets.QLabel(self.centralwidget)
        self.i1wLabel.setEnabled(True)
        self.i1wLabel.setObjectName("i1wLabel")
        self.gridLayout.addWidget(self.i1wLabel, 1, 0, 1, 1)
        self.i1wSpinner = QtWidgets.QSpinBox(self.centralwidget)
        self.i1wSpinner.setEnabled(True)
        self.i1wSpinner.setMinimum(5)
        self.i1wSpinner.setMaximum(150)
        self.i1wSpinner.setObjectName("i1wSpinner")
        self.gridLayout.addWidget(self.i1wSpinner, 1, 3, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMaximum(200)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 5, 3, 1, 1)
        self.i1dSlider = QtWidgets.QSlider(self.centralwidget)
        self.i1dSlider.setMinimum(1)
        self.i1dSlider.setMaximum(5)
        self.i1dSlider.setSingleStep(1)
        self.i1dSlider.setProperty("value", 1)
        self.i1dSlider.setOrientation(QtCore.Qt.Horizontal)
        self.i1dSlider.setObjectName("i1dSlider")
        self.gridLayout.addWidget(self.i1dSlider, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 3, 1, 1)
        self.i1hLabel = QtWidgets.QLabel(self.centralwidget)
        self.i1hLabel.setObjectName("i1hLabel")
        self.gridLayout.addWidget(self.i1hLabel, 2, 0, 1, 1)
        self.i1hSlider = QtWidgets.QSlider(self.centralwidget)
        self.i1hSlider.setMinimum(5)
        self.i1hSlider.setMaximum(150)
        self.i1hSlider.setProperty("value", 5)
        self.i1hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.i1hSlider.setObjectName("i1hSlider")
        self.gridLayout.addWidget(self.i1hSlider, 2, 1, 1, 1)
        self.i1hSpinner = QtWidgets.QSpinBox(self.centralwidget)
        self.i1hSpinner.setMinimum(5)
        self.i1hSpinner.setMaximum(150)
        self.i1hSpinner.setProperty("value", 5)
        self.i1hSpinner.setObjectName("i1hSpinner")
        self.gridLayout.addWidget(self.i1hSpinner, 2, 3, 1, 1)
        self.i1Group.addLayout(self.gridLayout)
        self.i1Group.setStretch(0, 2)
        self.i1Group.setStretch(1, 2)
        self.i1Group.setStretch(2, 4)
        self.verticalLayout.addLayout(self.i1Group)
        self.i1Group_2 = QtWidgets.QVBoxLayout()
        self.i1Group_2.setObjectName("i1Group_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.i1Group_2.addWidget(self.label_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.circle_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.circle_2.setChecked(True)
        self.circle_2.setObjectName("circle_2")
        self.intersection2Group = QtWidgets.QButtonGroup(MainWindow)
        self.intersection2Group.setObjectName("intersection2Group")
        self.intersection2Group.addButton(self.circle_2)
        self.horizontalLayout_2.addWidget(self.circle_2)
        self.rectangle_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rectangle_2.setObjectName("rectangle_2")
        self.intersection2Group.addButton(self.rectangle_2)
        self.horizontalLayout_2.addWidget(self.rectangle_2)
        self.i1Group_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.i2ySlider = QtWidgets.QSlider(self.centralwidget)
        self.i2ySlider.setMaximum(200)
        self.i2ySlider.setOrientation(QtCore.Qt.Horizontal)
        self.i2ySlider.setObjectName("i2ySlider")
        self.gridLayout_2.addWidget(self.i2ySlider, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.i2wSlider = QtWidgets.QSlider(self.centralwidget)
        self.i2wSlider.setEnabled(True)
        self.i2wSlider.setMinimum(5)
        self.i2wSlider.setMaximum(150)
        self.i2wSlider.setOrientation(QtCore.Qt.Horizontal)
        self.i2wSlider.setObjectName("i2wSlider")
        self.gridLayout_2.addWidget(self.i2wSlider, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.i2wLabel = QtWidgets.QLabel(self.centralwidget)
        self.i2wLabel.setEnabled(True)
        self.i2wLabel.setObjectName("i2wLabel")
        self.gridLayout_2.addWidget(self.i2wLabel, 1, 0, 1, 1)
        self.i2wSpinner = QtWidgets.QSpinBox(self.centralwidget)
        self.i2wSpinner.setEnabled(True)
        self.i2wSpinner.setMinimum(5)
        self.i2wSpinner.setMaximum(150)
        self.i2wSpinner.setObjectName("i2wSpinner")
        self.gridLayout_2.addWidget(self.i2wSpinner, 1, 3, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_6.setMaximum(200)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_2.addWidget(self.spinBox_6, 5, 3, 1, 1)
        self.i2dSlider = QtWidgets.QSlider(self.centralwidget)
        self.i2dSlider.setMinimum(1)
        self.i2dSlider.setMaximum(5)
        self.i2dSlider.setProperty("value", 1)
        self.i2dSlider.setOrientation(QtCore.Qt.Horizontal)
        self.i2dSlider.setObjectName("i2dSlider")
        self.gridLayout_2.addWidget(self.i2dSlider, 0, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_7.setMinimum(1)
        self.spinBox_7.setMaximum(5)
        self.spinBox_7.setProperty("value", 1)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_2.addWidget(self.spinBox_7, 0, 3, 1, 1)
        self.i2hLabel = QtWidgets.QLabel(self.centralwidget)
        self.i2hLabel.setObjectName("i2hLabel")
        self.gridLayout_2.addWidget(self.i2hLabel, 2, 0, 1, 1)
        self.i2hSlider = QtWidgets.QSlider(self.centralwidget)
        self.i2hSlider.setMinimum(5)
        self.i2hSlider.setMaximum(150)
        self.i2hSlider.setProperty("value", 5)
        self.i2hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.i2hSlider.setObjectName("i2hSlider")
        self.gridLayout_2.addWidget(self.i2hSlider, 2, 1, 1, 1)
        self.i2hSpinner = QtWidgets.QSpinBox(self.centralwidget)
        self.i2hSpinner.setMinimum(5)
        self.i2hSpinner.setMaximum(150)
        self.i2hSpinner.setProperty("value", 5)
        self.i2hSpinner.setObjectName("i2hSpinner")
        self.gridLayout_2.addWidget(self.i2hSpinner, 2, 3, 1, 1)
        self.i1Group_2.addLayout(self.gridLayout_2)
        self.i1Group_2.setStretch(0, 2)
        self.i1Group_2.setStretch(1, 2)
        self.i1Group_2.setStretch(2, 5)
        self.verticalLayout.addLayout(self.i1Group_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.i1dSlider.valueChanged['int'].connect(self.spinBox.setValue) # type: ignore
        self.spinBox.valueChanged['int'].connect(self.i1dSlider.setValue) # type: ignore
        self.i1ySlider.valueChanged['int'].connect(self.spinBox_2.setValue) # type: ignore
        self.spinBox_2.valueChanged['int'].connect(self.i1ySlider.setValue) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1wLabel.setVisible) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1wSlider.setVisible) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1wSpinner.setVisible) # type: ignore
        self.rectangle.clicked['bool'].connect(self.label.setHidden) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1dSlider.setHidden) # type: ignore
        self.rectangle.clicked['bool'].connect(self.spinBox.setHidden) # type: ignore
        self.circle.clicked['bool'].connect(self.i1wLabel.setHidden) # type: ignore
        self.circle.clicked['bool'].connect(self.i1wSlider.setHidden) # type: ignore
        self.circle.clicked['bool'].connect(self.i1wSpinner.setHidden) # type: ignore
        self.circle.clicked['bool'].connect(self.i1dSlider.setVisible) # type: ignore
        self.circle.clicked['bool'].connect(self.label.setVisible) # type: ignore
        self.circle.clicked['bool'].connect(self.spinBox.setVisible) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1hLabel.setVisible) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1hSlider.setVisible) # type: ignore
        self.rectangle.clicked['bool'].connect(self.i1hSpinner.setVisible) # type: ignore
        self.circle.clicked['bool'].connect(self.i1hLabel.setHidden) # type: ignore
        self.circle.clicked['bool'].connect(self.i1hSlider.setHidden) # type: ignore
        self.circle.clicked['bool'].connect(self.i1hSpinner.setHidden) # type: ignore
        self.i2dSlider.valueChanged['int'].connect(self.spinBox_7.setValue) # type: ignore
        self.i2wSlider.valueChanged['int'].connect(self.i2wSpinner.setValue) # type: ignore
        self.i2hSlider.valueChanged['int'].connect(self.i2hSpinner.setValue) # type: ignore
        self.i2ySlider.valueChanged['int'].connect(self.spinBox_6.setValue) # type: ignore
        self.spinBox_7.valueChanged['int'].connect(self.i2dSlider.setValue) # type: ignore
        self.i2wSpinner.valueChanged['int'].connect(self.i2wSlider.setValue) # type: ignore
        self.i2hSpinner.valueChanged['int'].connect(self.i2hSlider.setValue) # type: ignore
        self.spinBox_6.valueChanged['int'].connect(self.i2ySlider.setValue) # type: ignore
        self.circle_2.clicked['bool'].connect(self.label_10.setVisible) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2dSlider.setVisible) # type: ignore
        self.circle_2.clicked['bool'].connect(self.spinBox_7.setVisible) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.label_10.setHidden) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2dSlider.setHidden) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.spinBox_7.setHidden) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2wLabel.setHidden) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2wSlider.setHidden) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2wSpinner.setHidden) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2wLabel.setVisible) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2wSlider.setVisible) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2wSpinner.setVisible) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2hLabel.setHidden) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2hSlider.setHidden) # type: ignore
        self.circle_2.clicked['bool'].connect(self.i2hSpinner.setHidden) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2hSpinner.setVisible) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2hSlider.setVisible) # type: ignore
        self.rectangle_2.clicked['bool'].connect(self.i2hLabel.setVisible) # type: ignore
        self.i1wSlider.valueChanged['int'].connect(self.i1wSpinner.setValue) # type: ignore
        self.i1hSlider.valueChanged['int'].connect(self.i1hSpinner.setValue) # type: ignore
        self.i1hSpinner.valueChanged['int'].connect(self.i1hSlider.setValue) # type: ignore
        self.i1wSpinner.valueChanged['int'].connect(self.i1wSlider.setValue) # type: ignore
        self.u1Slider.valueChanged['int'].connect(self.spinBox_9.setValue) # type: ignore
        self.spinBox_9.valueChanged['int'].connect(self.u1Slider.setValue) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "U1"))
        self.label_5.setText(_translate("MainWindow", "Sketch"))
        self.label_3.setText(_translate("MainWindow", "End 1"))
        self.circle.setText(_translate("MainWindow", "Circle"))
        self.rectangle.setText(_translate("MainWindow", "Rectangle"))
        self.label_2.setText(_translate("MainWindow", "Y-Position"))
        self.label.setText(_translate("MainWindow", "Diameter"))
        self.i1wLabel.setText(_translate("MainWindow", "Width"))
        self.i1hLabel.setText(_translate("MainWindow", "Height"))
        self.label_8.setText(_translate("MainWindow", "End 2"))
        self.circle_2.setText(_translate("MainWindow", "Circle"))
        self.rectangle_2.setText(_translate("MainWindow", "Rectangle"))
        self.label_9.setText(_translate("MainWindow", "Y-Position"))
        self.label_10.setText(_translate("MainWindow", "Diameter"))
        self.i2wLabel.setText(_translate("MainWindow", "Width"))
        self.i2hLabel.setText(_translate("MainWindow", "Height"))
