name: hydraulics
channels:
  - conda-forge
dependencies:
  - python=3.10.5
  - jupyterlab=3
  - ipycanvas=0.12.0
  - ipyevents
  - branca
  - ipywidgets>=7.6
  - pythreejs=2.3.0
  - ipympl
  - matplotlib
  - voila